require 'trello'
require 'csv'
#require 'pry'

def get_list_id_for(trello_lists, current_state)
  trello_lists[current_state].id
end


Trello.configure do |config|
  config.developer_public_key = 'DEVELOPER_KEY' # replace with developer key generated by logging into Trello and visiting https://trello.com/1/appKey/generate
  config.member_token = 'MEMBER_TOKEN' # replace with member token obtained by copying your own developer key and inserting it in https://trello.com/1/connect?keyINSERTKEYHERE&name=MyApp&response_type=token&scope=read,write
end

user = Trello::Member.find('USERNAME') # replace with own username from Trello
board = Trello::Board.create({:name=>"PROJECT_NAME", :description=>"", :closed=>false,
  :starred=>true, :url=>"ANY_PROJECT_URL_BELONGING_TO_USERNAME", :organization_id=>nil,
  :prefs=>{"permissionLevel"=>"private", "voting"=>"disabled", "comments"=>"members",
    "invitations"=>"members", "selfJoin"=>false, "cardCovers"=>true, "cardAging"=>"regular",
    "calendarFeedEnabled"=>false, "background"=>"blue", "backgroundColor"=>"#0079BF",
    "backgroundImage"=>nil, "backgroundImageScaled"=>nil, "backgroundTile"=>false,
    "backgroundBrightness"=>"unknown", "canBePublic"=>true, "canBeOrg"=>true, "canBePrivate"=>true,
    "canInvite"=>true}}) #replace project name and project url with one from created by user


csv_text = File.read('CSV_FILE_DOT_CSV') #replace with .csv file
csv = CSV.parse(csv_text, :headers => true)
#raise csv.to_a.map {|row|  }.inspect
pivotal_tickets = csv.each.inject([]) do |result, csv_row|
  pivotal_ticket = csv_row.to_a.to_h # this is a Hash, eg. {"Title" => "Make coffee"}
  result << pivotal_ticket
end



current_states = pivotal_tickets.map { |ticket| ticket['Current State'] }

result_list = []
trello_lists = current_states.uniq.each.inject([]) do |result, current_state|
  result_list << Trello::List.create(name: current_state, board_id: board.id)
end

pivotal_tickets.first

user = Trello::Member.find('USERNAME') # replace with own username from Trello

def current_state(result_list, current_state)
  result_list.each do |result|
    if result.name == current_state
      return result.id
    end
  end
end


trello_cards = pivotal_tickets.each.inject([]) do |result, pivotal_ticket|

  current_state = pivotal_ticket["Current State"]
  list_id = current_state(result_list, current_state)
  desc = "#{pivotal_ticket["Description"]} \n Creado por #{pivotal_ticket["Requested By"]} #{pivotal_ticket["Task"]} #{pivotal_ticket["Task Status"]}"
  member_ids = pivotal_ticket["Owner email"]

  card = Trello::Card.create(list_id: list_id, name: pivotal_ticket["Title"], desc: desc, member_ids: user.id , card_labels: 'labels', due: 'due', pos: '')
  result << card
end


